# ~/.tmux.conf

# Use Ctrl-a instead of Ctrl-b
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g default-terminal "screen-256color"
set -sg escape-time 10
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Keep current path on split
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

##### COPY MODE #####

setw -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

##### STATUS BAR #####

# set -g status-position bottom
set -g status-style "bg=#3F704D,fg=#cdd6f4"

set -g status-left-length 40
set -g status-right-length 100

set -g status-left "#[fg=#ffffff]#S "
set -g status-right "#[fg=#ffffff]%Y-%m-%d #[fg=#ffffff]%H:%M"

setw -g window-status-current-format "#[fg=#ffffff,bg=#043927] #I:#W "
setw -g window-status-format "#[fg=#cdd6f4] #I:#W "

#setw -g window-status-current-format "#[fg=#1e1e2e,bg=#89b4fa,bold] #I:#W "
#setw -g window-status-format "#[fg=#cdd6f4] #I:#W "

set -g history-limit 100000
